apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
    name: blue
    environment: test
spec:
  containers:
  - name: blue
    image: amigoscode/kubernetes:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: labels-and-selector
spec:
  selector:
    name: blue
    environment: test
  ports:
  - port: 80
    targetPort: 80

